[fihrist]
= RHEL 7 ile Beraber Gelen Yeni RPM Özellikleri

Dokümanın bu kısmında Red Hat Enterprise Linux 6 ve 7. sürüm arasında dikkat edilmesi gereken farklar anlatılmaktadır.

* Anahtarlık ve imza denetimi için ``rpmkeys`` komutu eklendi. 
* SPEC dosyalarının sorgulanması ve taranması için ``rpmspec`` komutu eklendi. 
* Paketlerin imzalanması için ``rpmsign`` komutu eklendi. 
* ``%{lua:...}`` içerisinde gömülmüş betiklerde çağrılan ``posix.exec()`` ve ``os.exit()`` eklentileri, ``posix.fork()`` betikçisinin altsüreci olarak çağırılmadıkları sürece hata vereceklerdir.
* ``%pretrans`` betikçi hatası, paket kurulumunun atlanmasına neden olur.
* Betikçiler, çalışma zamanında makro ve sorgu biçimi (queryformat) şeklinde genişletilebilir.
* İşlem öncesi ve işlem sonraki betikçilerinin bağımlılıkları artık ``Requires(pretrans)`` ve ``Requires(posttrans)`` betikçileriyle ifade edilebilir. 
* Fazladan sıralama ipucularını ifade etmek için ``OrderWithRequires`` etiketi eklendi. Bu etiket, ``Requires`` etiketinin sözdizimini taklit eder ancak gerçek bağımlılıklar oluşturmaz. Sıralama ipuçlarında belirtilenler eğer işlem esnasında varsa ``Requires``'da belirtilmiş gibi ele alınırlar. 
* ``%license`` bayrağı ``%files`` kısmında kullanılabilirler. Tıpkı lisans dosyalarını işaretlerken tıpkı ``%doc`` gibi kullanılırlar, ancak ``-nodocs`` seçeneğinden etkilenmezler.
* Otomatik yama eklemek için kullanılan ``%autosetup`` makrosu, dilenirse bir versiyon kontrol sistemiyle beraber kullanılabilirler. 
* Otomatik bağımlılık oluşturucusu gömülü bir filtrelemeyle beraber genişletilebilir ve özelleştirilebilir bir şekilde yeniden yazıldı.
* OpenPGP V3 genel anahtarları artık desteklenmeyecektir. 
