[[yazilimi-paketlemeye-hazirlamak]]
= Yazılımı Paketlemeye Hazırlamak

Bu bölüm bir RPM paketçisinin bilmesi gereken kaynak kodu ve yazılım oluşturmak gibi konuları içerir. 

[[kaynak-kodu-nedir]]
== Kaynak kodu nedir?

**Kaynak kodu** bir dosyanın bilgisayara nasıl derlenmesi gerektiğinin anlatıldığı ve insanlar tarafından okunabilen talimatlardır. Kaynak kodları, bir programlama dili aracılığıyla hazırlanır. Bkz:
ifdef::community[https://tr.wikipedia.org/wiki/Programlama_dili[Programlama Dili]]
ifdef::rhel[Programlama Dili]

Bu klavuz farklı programlama dillerinde yazılmış ``Merhaba Dünya`` programının üç sürümünü ele alır. Farklı programlama dilleriyle yazılmış bu programlar farklı şekilde paketlenir ve bir RPM paketçisinin karşılaşacağı üç farklı durumu özetler.

Not: Yüzden fazla programlama dili vardır. Bu belge, yalnızca üç tanesini ele alır fakat bir kuşbakışı için yeterlidir. 

https://www.gnu.org/software/bash/[Bash] ile yazılmış bir ``Merhaba Dünya``:

``belaba``

[source,bash]
----
#!/bin/bash

printf "Merhaba Dünya\n"

----

https://www.python.org/[Python] ile yazılmış bir ``Merhaba Dünya``:

``pelaba.py``

[source,python]
----
#!/usr/bin/env python

print("Merhaba Dünya")

----

ifdef::community[https://tr.wikipedia.org/wiki/C_(programlama_dili)[C]]
ifdef::rhel[C]
ile yazılmış bir ``Merhaba Dünya``:

``celaba.c``

[source,c]
----
#include <stdio.h>

int main(void) {
    printf("Merhaba Dünya\n");
    return 0;
}

----

Bu üç programın da amacı komut satırına "Merhaba Dünya" yazmaktır. 

Not: Programlamayı bilmek yazılım paketlemek için gerekli değildir ama faydalıdır.

[[programlar-nasil-yapilir]]
== Programlar Nasıl Yapılır?

İnsan tarafından okunabilen kaynak kodunu bilgisayarın takip ettiği talimatları sunan makine koduna çevirmek için pek çok yöntem vardır. Bununla birlikte, bu yöntemler şu üç tanesine indirgenebilir:

1. Program yerel olarak derlenebilir.
2. Program ham hâliyle yorumlanabilir.
3. Program bayt derleme ile yorumlanabilir. 

[[yerel-derlenmis-kod]]
=== Yerel Olarak Derlenmiş Kod

**(Mimariye) Yerel derlenmiş** yazılım, makine koduna dönüştürülen bir programlama dilinde yazılmış yazılımdır. Bu tarz yazılımlar tek başına, çalıştırılabilir ikili dosyalar olarak çalıştırılabilir. 

Bu yolla derlenmiş RPM paketleri belirli bir 
ifdef::community[https://tr.wikipedia.org/wiki/Bilgisayar_organizasyonu[mimariye]]
ifdef::rhel[mimariye]
yöneliktir. Yani, sizin 64 bit (x86_64) mimarisine yönelik hazırladığınız yazılım 32 bit (x86) mimarisinde çalıştırılamaz. Bu yazılımların paketlerinin isimlerinde hangi mimariyi hedef aldığı belirtilir. 

[[yorumlanan-kod]]
=== Yorumlanan Kod

https://www.gnu.org/software/bash/[bash] ve https://www.python.org/[Python] gibi bazı programlama dilleri doğrudan makine diline derlenmez. Bunun yerine, bu dillerin dillerde yazılan kaynak kodları herhangi bir ön dönüşüme tabii tutulmaksızın adım adım çalıştılır. Bu kodları bir
ifdef::community[https://tr.wikipedia.org/wiki/Yorumlayıcı[Dil Yorumlayıcısı]]
ifdef::rhel[Dil Yorumlayıcısı]
tarafından veya Dil Sanal Makinesi tarafından işlenir. 

Bu yazılımlar belirli bir 
ifdef::community[https://tr.wikipedia.org/wiki/Bilgisayar_organizasyonu[mimariye]]
ifdef::rhel[mimariye]
yönelik değildir. Dolayısıyla, bu yazılımların RPM paketlerinin isminde ``noarch`` ibaresi bulunur.

// İki tip yorumlanan dil vardır: bayt derlenenler ve ham hâliyle yorumlananlar. Bu programların inşa süreçleri iki tip içinde farklıdır. 

Yorumlanan bir dil ya *bayt olarak derlenebilir* ya da *ham hâliyle yorumlanabilir*. Bu iki farklı tipin inşa süreci ve paketleme yöntemi birbirinden farklıdır. 


==== Ham olarak yorumlanan programlar
Ham hâliyle yorumlanan dillerin programlarının derlenmeye ihtiyacı yoktur, direkt yorumlanabilirler. 

==== Bayt derlenen programlar
Bayt derlenen dillerin bayt koduna derlenmeye ihtiyacı vardır. Bu programlar dil sanal makineleri tarafından çalıştırılırlar. 

Not: Ham olarak yorumlanmak veya bayt koduna derlenmek arasında bir seçenek sunar.

// This difference reflects on the packaging procedure. Some languages give a choice: they can be raw-interpreted or byte-compiled. (Bu kısmı çevirmiyorum)

// Tamamen yorumlanan programlama dillerinde hazırlanan programlar belli bir https://tr.wikipedia.org/wiki/Bilgisayar_organizasyonu[mimariye] yönelik değildir. Dolayısıyla RPM paketlerinin isimlerinde ``noarch`` ibaresi bulunur.

[[yazilimi-kaynaktan-insa-etmek]]
== Yazılımı Kaynaktan İnşa Etmek

Bu kısım, kaynak kodundan bir yazılımı inşa etmeyi açıklar. 

* Derlenen dillerde yazılan yazılımlar, bir **inşa** sürecinden geçer ve makine kodu üretilir. Bu süreç, yaygın olarak **derleme** veyahut **çeviri** olarak isimlendirilir, programlama dilleri açısından farklılık gösterir. Derleme sonrasında program *çalıştırılır* veyahut *yürütülür* ve yazılımcının belirlediği görevleri yerine getirir. (Ç.N: Orijinal belgede *run* ve *executed* ifadelerini sırasıyla *çalıştırma* ve *yürütme* olarak çevirdim.) 
* Ham olarak yorumlanan dillerle yazılmış dillerde yazılım inşa edilmez, doğrudan çalıştırılır. 
* Bayt derlenerek yorumlanan dillerle yazılmış dillerde ise kaynak kodu bayt kodu olarak derlenir ve dil sanal makinesi tarafından çalıştırılır. 

[[yerel-derlenen-kodu-kaynaktan-insa-etmek]]
=== Yerel Derlenen Kod

Bu örnekte 
ifdef::community[https://tr.wikipedia.org/wiki/C_(programlama_dili)[C]]
ifdef::rhel[C]
ile yazılmış ``celaba.c``dosyasını çalıştırılabilir bir dosyaya dönüştüreceksiniz. 

``celaba.c``

[source,c]
----
#include <stdio.h>

int main(void) {
    printf("Merhaba Dünya\n");
    return 0;
}

----

[[elle-insa]]
==== Elle İnşa

ifdef::community[https://tr.wikipedia.org/wiki/C_(programlama_dili)[C]]
ifdef::rhel[C]
kaynak kodlarını derlemek için kullanılan "GNU Derleyici Koleksiyonu"nu (https://gcc.gnu.org/[GCC]) çalıştıracağız. 

[source,bash]
----
gcc -g -o celaba celaba.c

----

Çıktı olarak gelen ``celaba`` dosyasını çalıştırın.

[source,bash]
----
$ ./celaba
Merhaba Dünya

----

İşte, hepsi bu. Yerel olarak derlenen bir yazılımı kaynak kodundan çalıştırıp derlemiş oldunuz.

==== Otomatik İnşa

Kaynak kodunu elle inşa etmek yerine inşa sürecini otomatikleştirebilirsiniz. Büyük ölçekli projeler için yaygın bir uygulamadır. Otomatik inşa, ``Makefile`` isimli bir dosya oluşturup http://www.gnu.org/software/make/[GNU ``make``] aracını çağırmakla gerçekleştirilebilir.

Otomatik bir inşa kurmak için, ``celaba.c`` ile aynı klasörde ``Makefile`` isimli bir dosya oluşturun:

``Makefile``

[source,makefile]
----
celaba:
        gcc -g -o celaba celaba.c

clean:
        rm celaba

----

Bu yazımlımı inşa etmek için, yalnızca ``make`` komutunu çalıştırın:


[source,bash]
----
$ make
make: 'celaba' is up to date.

----

Daha önceden yapılmış bir inşayı temizlemek için ``make clean`` komutunu çalıştırın, ardından tekrar ``make`` komutunu çalıştırın:

[source,bash]
----
$ make clean
rm celaba

$ make
gcc -g -o celaba celaba.c

----

Şimdi, hiçbir şey olmayacağını bile bile tekrar bir inşaya teşebbüs edelim:

[source,bash]
----
$ make
make: 'celaba' is up to date.

----

Güzel, programı çalıştırabiliriz:

[source,bash]
----
$ ./celaba
Merhaba Dünya

----

Hem elle, hem de otomatik olarak bir programı derlemiş bulunmaktasınız. 

[[yorunlanan-kodu-kaynaktan-insa-etmek]]
=== Yorumlanan Kod

İnceleyeceğimiz iki örnekten birisi https://www.python.org/[Python] ile yazılmış bayt olarak derlenen bir program, diğeri ise https://www.gnu.org/software/bash/[Bash] ile yazılmış ve ham olarak yorumlanan başka bir program.

[NOTE]
====
İki örnekte de göreceğiniz, dosyanın başındaki ``#!`` satırı programlama dilinin bir parçası değildir ve 
ifdef::community[https://en.wikipedia.org/wiki/Shebang_%28Unix%29[mevzu (shebang)]]
ifdef::rhel[mevzu (shebang]
olarak anılır. (Bağlantı İngilizcedir.)

ifdef::community[https://en.wikipedia.org/wiki/Shebang_%28Unix%29[Mevzular]]
ifdef::rhel[Mevzular]
bir yazı dosyasının çalıştırılabilir bir dosya olarak ele alınmasına izin verir. Sistemin program yükleyicisi bu satırı özellikle arar ve bu satır üzerinde bulunan ikili programla çalıştır ki bu ilgili programlama dilinin yorumlayıcısıdır.
====

[[bayt-derlenen-kod]]
==== Bayt Derlenen Kod 

Bu örnekte, Python ile yazılmış ``pelaba.py`` isimli programı bayt koduna dönüştüreceğiz, bu bayt kodu Python dili sanal makinesi tarafından derlenecek. Python kodları istenirse ham yorumlanabilir ancak bayt derlenen sürümü daha hızlıdır. Dolayıcıyla, RPM paketçileri son kullanıcıya paketleri dağıtırken bayt derlenen sürümünü tercih eder. 

``pello.py``

[source,python]
----
#!/usr/bin/env python

print("Merhaba Dünya")

----

Bayt derlenen programlar için gerekli diğer dillerden daha farklıdır. Bu yöntem dil üzerine kuruludur, dilin sanal makinesini gerektirir ve kullanılan araçlar/süreçler dile aittir. 

NOTE: https://www.python.org/[Python] çoğunlukla bayt olarak derlenir, ancak bu bahsettiğimiz şekilde değil. Bahsi geçen yöntem topluluk standarlarına uyumlu olmayı değil sade olmayı gerektirir. Gerçek dünyada kullanılan Python rehberleri için şu bağlantıya bakabilirsiniz: 
https://docs.python.org/2/library/distribution.html[Software Packaging and
Distribution (İngilizce)].

Bayt derlenen ``pelaba.py``:

[source,bash]
----
$ python -m compileall pello.py

$ file pello.pyc
pello.pyc: python 2.7 byte-compiled

----

``pello.pyc`` bayt kodunu çalıştırın:

[source,bash]
----
$ python pello.pyc
Hello World

----

[[ham-yorumlanan]]
==== Ham Hâlde Yorumlanan Kod

Bu örneğimizde ise https://www.gnu.org/software/bash/[bash] ile ham yorumlanan ``belaba`` programımızı inceleyeceğiz. 

``belaba``

[source,bash]
----
#!/bin/bash

printf "Merhaba Dünya\n"

----
_Bash_ gibi kabuk betik dilleriyle yazılmış programlar ham yorumlanır. Hâliyle sadece dosyayı kaynak kdoundan çalıştırılabilir yapmanız ve çalıştırmanız gerekmektedir:

[source,bash]
----
$ chmod +x belaba
$ ./belaba
Merhaba Dünya

----

[[yazilimi-yamalamak]]
== Yazılımı Yamalamak

**Yama**, başka bir kaynak kodunu güncelleyen bir kaynak kodudur. "__diff__" şeklinde formatlanmıştır zira bu format iki farklı versiyon arasındaki farkı gösterir. "__diff__" formatı, ``diff`` isimli bir araç aracılığıyla oluşturulur ki daha sonra http://savannah.gnu.org/projects/patch/[patch] isimli bir araç aracılığıyla kaynak koduna uygulanır. 

Not: Yazılım geliştirileri kendi kodlarını kontrol etmek için çoğunlukla https://git-scm.com/[git] gibi Versiyon Kontrol Sistemlerini kullanır. Bu tür araçların __diff__ yaratmak ve yamaları uygulamak için kendi yöntemleri vardır. 

Aşağıdaki örnekte, orijinal kaynak kodundan ``diff`` kullanarak yeni bir yama oluşturuyoruz ve ``patch`` kullanarak uyguluyoruz. Yamalamadan, daha sonraları xref:spec-dosyalari-ile-calismak[] kısmında yararlanacağız. 

Peki yamalamanın RPM paketlemekle ne alakası var? Paketlerken, orijinal kaynak kodunu olduğu değiştirmek yerine onu koruyup üzerine yama uygulamayı tercih ederiz. 

``celaba.c`` için bir yama hazırlayalım:

Esas kaynak kodunu koruyalım: 

+
[source,bash]
----
$ cp celaba.c celaba.c.orig

----
+
Bu, orijinal kaynak kodunu muhafaza etmek için yaygın bir yöntemdir. 
+
. ``celaba.c``'yi değiştirelim:
+
[source,c]
----
#include <stdio.h>

int main(void) {
    printf("Yeni yamamdan selam dünya!\n");
    return 0;
}

----
+
``diff`` aracını kullanarak bir yama oluşturalım:
+
. Not: ``diff`` aracını kullanırken birden fazla argüman kullandık. Bu argümanlar hakkında bilgi almak için, ``diff`` ile ilgili belgeleri araştırınız. 
+
[source,diff]
----
$ diff -Naur celaba.c.orig celaba.c
--- cello.c.orig        2016-05-26 17:21:30.478523360 -0500
+++ cello.c     2016-05-27 14:53:20.668588245 -0500
@@ -1,6 +1,6 @@
 #include<stdio.h>

 int main(void){
-    printf("Hello World!\n");
+    printf("Hello World from my very first patch!\n");
     return 0;
 }
----
+
. ``-`` ile başlayan satırlar, orijinal kaynak kodunda yer alan ve çıkarılmış kodlardır. ``+`` ile yer alan kodlar ise çıkarılan kodların yerine geçer. 
+

. Yamayı bir dosyaya kaydedelim:
+
[source,bash]
----
$ diff -Naur celaba.c.orig celaba.c > celaba-ciktisi-ilk-yama.patch
----
+
. Orijinal ``celaba.c`` dosyasını geri getirelim:
+
[source,bash]
----
$ cp celaba.c.orig celaba.c
----
+
Esas ``celaba.c`` dosyasını geri getirdik. Bunun nedeni, bir RPM paketi inşa edileceği zaman düzenlenmiş dosya yerine esas dosyanın kullanılmasıdır. Daha fazla bilgi için: xref:spec-dosyalari-ile-calismak[]

``celaba.c`` dosyasını, ``celaba-ciktisi-ilk-yama.patch`` dosyasını kullanarak, yamalanmış dosyayı ``patch`` komutuna yönlendirin:

[source,bash]
----
$ patch < celaba-ciktisi-ilk-yama.patch
patching file celaba.c
----

``celaba.c`` dosyasının içeriği, gördüğünüz üzere yamayla değişti:

[source,bash]
----
$ cat celaba.c
#include<stdio.h>

int main(void){
    printf("Yeni yamamdan selam dünya!\n");
    return 0;
}
----

Yamalanmış ``celaba.c`` dosyasını derleyip çalıştıralım:


[source,bash]
----
$ make clean
rm celaba

$ make
gcc -g -o celaba celaba.c

$ ./celaba
Yeni yamamdan selam dünya!
----

Tebrikler! Bir yama oluşturdunuz, sonra programı yamaladınız, yamalı programı derlediniz ve çalıştırmış oldunuz!

[[ihtiyari-yapilar-kurma]]
== İhtiyari Yapılar Kurma

ifdef::community[https://tr.wikipedia.org/wiki/Linux[Linux]]
ifdef::rhel[Linux]
ve Unix benzeri işletim sistemlerinin büyük bir avantajı 
ifdef::community[https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard[Dosya Sistemi Hiyerarşisi Standartlarıdır]]
ifdef::rhel[Dosya Sistemi Hiyerarşisi Standartlarıdır]. Bu standartlar, hangi dizinde hangi dosyanın depolanacağınıbelirtir. RPM paketlerinden kurulan dosyalar ise Dosya Sistemi Hiyerarşisine uygun olmalıdır. Örneğin, çalıştırılabilir bir dosya 
ifdef::community[https://en.wikipedia.org/wiki/PATH_%28variable%29[PATH]]
ifdef::rhel[PATH] 
değişkeninde belirtilen bir dizin altında tutulmalıdır. 

Bu belgenin bağlamında, bir __İhtiyari Yapı__ RPM aracılığıyla sisteme kurulan herhangi bir şeydir. Bu RPM ve sistem için bir betik, paketin içerdiği kaynak kodundan derlenen bir ikili bir dosya, önceden derlenmiş ikili bir dosya veya başka bir dosya olabilir. 

Biz, sisteme __İhtiyari Yapıları__ yerleştirmenin iki popüler yolunu keşfedeceğiz: ``install`` veya ``make install`` kullanmak.

[[install-komutu]]
=== Install komutunu kullanmak

Kimi zaman inşa sürecini http://www.gnu.org/software/make/[GNU make]  gibi araçlarla otomatikleştirmek pek iyi bir fikir olmayabilir. Mesela, derleyeceğimiz program öyle basittir ki böyle gösterişli şeylere pek ihtiyaç duymaz. Bu ve bunun gibi durumlarda paketçiler çoğunlukla http://www.gnu.org/software/coreutils/coreutils.html[coreutils] tarafından sunulan ``install`` komutunu tercih ederler. Bu komut sözünü ettiğimiz yapıları dosya sisteminde belirli bir dizine, belirli izinlerle yerleştirir. 

Aşağıdaki örnekte daha önce hazırladığımız ``belaba`` dosyasını bir ihtiyari yapı olarak sistemimize kuracağız. Yalnız dikkat etmeniz gereken bir şey, bu kurulum için http://www.sudo.ws/[sudo] veya root yetkilerine sahip olmanız gerektiğidir. 

Bu örnekte, ``belaba`` dosyasını ``/usr/bin`` içerisine ``install`` komutuyla yerleştireceğiz, elbette ki çalıştırmak için gerekli izinlerle beraber:


[source,bash]
----
$ sudo install -m 0755 belaba /usr/bin/belaba

----
``belaba`` isimli dosyamız 
ifdef::community[https://en.wikipedia.org/wiki/PATH_%28variable%29[$PATH]]
ifdef::rhel[$PATH] 
değişkeninde listelenmiş bir dizinde bulunmakta. Artık herhangi bir dizinde, ``belaba`` dosyasını bütün konumu belirtmeden çalıştırabilirsiniz. 


[source,bash]
----
$ cd ~

$ belaba
Merhaba Dünya!

----

[[make-install]]
=== Make Install komutunu kullanmak

Bir yazılımı otomatikleştirilmiş bir şekilde kurmak için popüler bir yöntem ``make install`` komutunu kullanmaktır. Bu yöntem, ``Makefile`` içerisinde ihtiyari yapıların nasıl kurulması gerektiğini belirtmenizi gerektirir. 

Not: Çoğunlukla ``Makefile`` paketçi tarafından değil geliştirici tarafından hazırlanır. 

``Makefile`` içerisine ``install`` kısmını ekleyin:

``Makefile``

[source,makefile]
----
cello:
        gcc -g -o celaba celaba.c

clean:
        rm cello

install:
        mkdir -p $(DESTDIR)/usr/bin
        install -m 0755 celaba $(DESTDIR)/usr/bin/celaba

----

https://www.gnu.org/software/make/manual/html_node/DESTDIR.html[$(DESTDIR)] değişkeni http://www.gnu.org/software/make/[GNU make] içerisine yerleştirilmiş bir değişkendir ve çoğunlukla kurulum dizininin kök dizin dışında neresi olması gerektiğini belirtir. 

Artık, ``Makefile`` dosyasını yalnızca dosyayı derlemek için değil, hedef sisteme kurmak için de kullanabilirsiniz. 

``celaba.c``'yi derleyip kurmak için: 


[source,bash]
----
$ make
gcc -g -o celaba celaba.c

$ sudo make install
install -m 0755 celaba /usr/bin/celaba

----
``celaba`` programını 
ifdef::community[https://en.wikipedia.org/wiki/PATH_%28variable%29[$PATH]]
ifdef::rhel[$PATH] 
değişkeni içerisinde tanımlanmış dizinlerden birisine eklemiş oldunuz. Artık, ``celaba``'yı tam konumunu belirtmeden dilediğiniz gibi çalıştırabilirsiniz. 

[source,bash]
----
$ cd ~

$ celaba
Merhaba Dünya!

----

Sisteminize inşa edilmiş bir yapıyı belirtilmiş bir konuma kurmuş bulunmaktasınız. 

[[kodu-paketlemek-icin-hazirlamak]]
== Kodu Paketlemek İçin Hazırlamak

Not: Bu bölümde hazırladığımız kodları https://github.com/Tarbetu/rpm-paketleme-rehberi/tree/master/örnek-kod[burada] bulabilirsiniz.

Geliştiriciler yazılımlarını çoğunlukla sıkıştırılmış arşivler içerisinde dağıtırlar ki bunlar paketleme için kullanılırlar. Bu bölümde sıkıştırılmış arşivler hazırlayacaksınız. 

Not: Kaynak kodu arşivleme işi çoğunlukla RPM paketçisinin görevi değildir, geliştirici tarafından yapılır. Paketçi, hazır kaynak kodu arşivleriyle çalışır. 



Yazılımlar bir 
ifdef::community[https://tr.wikipedia.org/wiki/Yazılım_lisansı[yazılım lisansı]]
ifdef::rhel[yazılım lisansı] aracılığıyla lisanslanmalıdır. Biz örnek olarak https://www.gnu.org/licenses/quick-guide-gplv3.html[GPLv3] lisansını ele alacağız. Lisans metnini örnek programlarımızın ``LICENCE`` dosyasında sunacağız. Bir RPM paketçisi, paketlerken lisans dosyaları ile ilgilenmelidir. 

Aşağıdaki örnekte bir lisans dosyası oluşturduk:

[source,bash]
----
$ cat /tmp/LICENSE
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

----

[[tarballa-kaynak-kodu-eklemek]]
== Tarball İçerisine Kaynak Kodu Eklemek

Ç.N: ``Tarball``, kaynak kodlarını içinde bulunduran ve uzantısında "tar" bulunan (Örn: .tar.gz)  arşiv dosyalarına verilen isim. Literatürde bu şekilde yer aldığından, motamot çevirisi de "Tartopu" gibi anlamsız bir şeye tekabül ettiğinden ``tarball`` kelimesini kabul ediyorum. Eğer ``tarball`` yerine geçecek iyi bir fikriniz varsa muhakkak bana bildirin. 

Aşağıdaki örneklerde, üç ``Merhaba Dünya`` programının her birisini https://www.gnu.org/software/gzip/[gzip] ile sıkıştırılmış tarballlara ekliyoruz. Yazılımlar çoğunlukla paketlenmeden önce bu şekilde yayınlanırlar.

[[belaba]]
=== belaba

__belaba__ yazılımı, https://www.gnu.org/software/bash/[bash] ile ``Merhaba Dünya`` yazmamızı sağlıyor. Bu yazılım kendi içerisinde yalnızca ``belaba`` kabuk betiğini içeriyor ve oluşturacağımız ``.tar.gz`` arşivinde ``LICENCE`` dışında yalnızca bu betik var. Bu yazılımın sürüm numarasını ``0.1`` olarak düşünebiliriz. 

__bello__ yazılımını dağıtıma hazırlayalım:

. Dosyaları bir dizine yerleştirin: 
+
[source,bash]
----
$ mkdir /tmp/belaba-0.1

$ mv ~/bello /tmp/belaba-0.1/

$ cp /tmp/LICENSE /tmp/belaba-0.1/

----

. Arşiv dosyasını oluşturun ve ``~/rpmbuild/SOURCES/`` altına taşıyın:
+
[source,bash]
----
$ cd /tmp/

$ tar -cvzf belaba-0.1.tar.gz belaba-0.1
bello-0.1/
bello-0.1/LICENSE
bello-0.1/belaba

$ mv /tmp/belaba-0.1.tar.gz ~/rpmbuild/SOURCES/

----

[[pelaba]]
=== pelaba

__pelaba__ yazılımı, https://www.python.org/[Python] ile ``Merhaba Dünya`` yazmamızı sağlıyor. Bu yazılım kendi içerisinde yalnızca ``pelaba`` betiğini içeriyor ve oluşturacağımız ``.tar.gz`` arşivinde ``LICENCE`` dışında yalnızca bu betik var. Bu yazılımın sürüm numarasını ``0.1.1`` olarak düşünebiliriz. 

__pelaba__ yazılımını dağıtıma hazırlayalım:

. Dosyaları bir dizine yerleştirin: 
+
[source,bash]
----
$ mkdir /tmp/pello-0.1.1

$ mv ~/pello.py /tmp/pello-0.1.1/

$ cp /tmp/LICENSE /tmp/pello-0.1.1/

----

. Arşiv dosyasını oluşturun ve ``~/rpmbuild/SOURCES/`` altına taşıyın:
+
[source,bash]
----
$ cd /tmp/

$ tar -cvzf pello-0.1.1.tar.gz pello-0.1.1
pello-0.1.1/
pello-0.1.1/LICENSE
pello-0.1.1/pello.py

$ mv /tmp/pello-0.1.1.tar.gz ~/rpmbuild/SOURCES/

----

[[celaba]]
=== celaba

__celaba__ yazılımı, 
ifdef::community[https://tr.wikipedia.org/wiki/C_(programlama_dili)[C]]
ifdef::rhel[C]
ile ``Merhaba Dünya`` yazmamızı sağlıyor. Bu yazılım kendi içerisinde yalnızca ``celaba.c``'yi ve ``Makefile`` dosyasını içeriyor ve oluşturacağımız ``.tar.gz`` arşivinde ``LICENCE`` dışında yalnızca iki dosya olacak. Bu yazılımın sürüm numarasını ``1.0`` olarak düşünebiliriz. 

``patch`` dosyasını arşiv ile beraber dağıtıma çıkartmadığımıza dikkat edin. RPM Paketleyicisi yamayı RPM derlenirken uygular. Yama, ``.tar.gz`` dosyası ile beraber ``~/rpmbuild/SOURCES/`` dizinine yerleştirilecek.

__celaba__ yazılımını dağıtıma hazırlayalım:


. Dosyaları bir dizine yerleştirin: 
+
[source,bash]
----
$ mkdir /tmp/cello-1.0

$ mv ~/cello.c /tmp/cello-1.0/

$ mv ~/Makefile /tmp/cello-1.0/

$ cp /tmp/LICENSE /tmp/cello-1.0/

----

. Arşiv dosyasını oluşturun ve ``~/rpmbuild/SOURCES/`` altına taşıyın:
+
[source,bash]
----
$ cd /tmp/

$ tar -cvzf cello-1.0.tar.gz cello-1.0
cello-1.0/
cello-1.0/Makefile
cello-1.0/cello.c
cello-1.0/LICENSE

$ mv /tmp/cello-1.0.tar.gz ~/rpmbuild/SOURCES/

----

. Yamayı uygulayın
+
[source,bash]
----
$ mv ~/cello-output-first-patch.patch ~/rpmbuild/SOURCES/

----

Ve kaynak kodlarınız RPM'e paketlenmek üzere hazır!
